project:
  type: website

website:
  title: "Izel Fourie Sørensen"

  navbar:
      left:
      - href: projects.qmd
        text: Portfolio
      - href: resume.qmd
        text: Resume
        
      right:
      - icon: github
        href: https://github.com/IzelFourie
      - icon: linkedin
        href: https://linkedin.com/in/izel-fourie-sørensen
format:
  html:
    code-fold: true
    code-tools: true
    theme: cosmo
    css: styles.css
execute: 
  warning: false
  message: false
editor: visual

